CREATE TABLE ACCOUNT(
	BUSI_NUM			CHAR(20),
	FACTORY			CHAR(20),
	TRADE_BANK		CHAR(20),
	ACCOUNT_NUM		CHAR(20),
	PRIMARY KEY(BUSI_NUM),
	FOREIGN KEY(BUSI_NUM) REFERENCES custom(BUSI_NUM) ON DELETE CASCADE ON UPDATE CASCADE
);

DESC ACCOUNT;

SELECT * FROM ACCOUNT;


INSERT INTO ACCOUNT(	BUSI_NUM,
							FACTORY,
							TRADE_BANK,
							ACCOUNT_NUM)
VALUES('aa',
		 'aa1',
		 'aa2',
		 'aa3');
		 
		 
SELECT * FROM ACCOUNT;

DESC ACCOUNT;